In [64]:
import pandas as pd
import numpy as np

In [116]:
#Exercici 1: Descarrega el data set Airlines Delay (muestra de 20), Explora les dades (columnas) que conté

archivo = pd.read_csv('DelayedFlights.csv')
archivo[:20]

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0
13,21,2008,1,3,4,1657.0,1625,1754.0,1735,WN,...,5.0,5.0,0,N,0,7.0,0.0,0.0,0.0,12.0
14,22,2008,1,3,4,1900.0,1840,1956.0,1950,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
15,23,2008,1,3,4,1039.0,1030,1133.0,1140,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
16,25,2008,1,3,4,1520.0,1455,1619.0,1605,WN,...,2.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
17,26,2008,1,3,4,1422.0,1255,1657.0,1610,WN,...,6.0,6.0,0,N,0,40.0,0.0,0.0,0.0,7.0
18,27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,...,3.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
19,30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,...,6.0,7.0,0,N,0,5.0,0.0,0.0,0.0,59.0

In [36]:
#Explora les dades (columnas) que conté.
#El archivo cuenta con los siguientes columnas:

archivo.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [117]:
#Exercici 1: queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció
#Respuesta: 
#Columnas que no considero relevantes: razón por la cual no me parecen relevantes 
#Year: todos son 2008
#Cancelled: Lo que estamos analizando son retrasos, no si se canceló o no. 
#Unamed: No me aporta información y clsifica los datos por números, que ya estaban clasificados. 
#Codigo de cancelación: No estoy analizando cancelación sino retraso 

newarchivo = archivo.drop(['Year', 'Unnamed: 0', 'Cancelled', 'CancellationCode'], axis='columns')

In [53]:
#Exercici 1: Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

aarchivo = newarchivo.sample(n=200000)
aarchivo[:20]

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
962501,6,8,7,1236.0,1205,1342.0,1309,UA,443,N331UA,...,DEN,680,7.0,11.0,0,8.0,0.0,2.0,0.0,23.0
1041147,6,8,7,905.0,845,1130.0,1110,AA,661,N253AA,...,DFW,852,13.0,11.0,0,20.0,0.0,0.0,0.0,0.0
281708,2,22,5,1446.0,1430,1711.0,1650,DL,150,N186DN,...,JFK,760,18.0,40.0,0,0.0,16.0,5.0,0.0,0.0
559789,3,14,5,1237.0,1135,1410.0,1307,CO,499,N75854,...,DEN,861,10.0,17.0,0,62.0,0.0,1.0,0.0,0.0
1326529,8,22,5,1908.0,1842,2219.0,2142,UA,302,N928UA,...,ALB,723,4.0,30.0,0,11.0,0.0,11.0,0.0,15.0
296573,2,9,6,1719.0,1706,1929.0,1914,FL,333,N174AT,...,ATL,665,5.0,10.0,0,13.0,0.0,2.0,0.0,0.0
1564374,10,12,7,2258.0,2235,705.0,703,UA,188,N421UA,...,PHL,2521,6.0,13.0,0,NaN,NaN,NaN,NaN,NaN
1400926,8,20,3,1902.0,1800,2253.0,2135,AA,2094,N526AA,...,RSW,1017,4.0,36.0,0,0.0,62.0,16.0,0.0,0.0
1570410,10,3,5,911.0,845,1049.0,1026,US,945,N725UW,...,CLT,500,6.0,13.0,0,23.0,0.0,0.0,0.0,0.0
992043,6,7,6,2129.0,2121,2249.0,2244,EV,4495,N748EV,...,DAB,366,2.0,24.0,0,NaN,NaN,NaN,NaN,NaN
218147,2,29,5,1443.0,1430,1548.0,1550,WN,2377,N601WN,...,RNO,345,4.0,9.0,0,NaN,NaN,NaN,NaN,NaN
1109991,7,30,3,951.0,945,1102.0,1105,WN,3069,N231WN,...,PHX,370,4.0,8.0,0,NaN,NaN,NaN,NaN,NaN
641262,4,4,5,2257.0,2215,625.0,556,US,18,N668AW,...,JFK,2153,6.0,11.0,0,29.0,0.0,0.0,0.0,0.0
1210716,7,25,5,913.0,720,1319.0,1100,MQ,4881,N734EK,...,LGA,963,4.0,32.0,0,113.0,0.0,26.0,0.0,0.0
596953,4,25,5,2134.0,2055,2321.0,2250,WN,2266,N311SW,...,SMF,647,4.0,5.0,0,5.0,0.0,0.0,0.0,26.0
675754,4,27,7,1124.0,1115,1252.0,1245,MQ,4281,N813AE,...,MEM,860,7.0,7.0,0,NaN,NaN,NaN,NaN,NaN
164470,1,1,2,2210.0,2143,26.0,26,AS,89,N569AS,...,ANC,1449,4.0,14.0,0,NaN,NaN,NaN,NaN,NaN
1916868,12,12,5,1823.0,1650,2153.0,1959,B6,1203,N665JB,...,RSW,1144,6.0,48.0,0,93.0,0.0,21.0,0.0,0.0
1450031,9,4,4,1655.0,1359,1942.0,1640,YV,7321,N154SF,...,TYS,475,5.0,15.0,0,0.0,0.0,6.0,0.0,176.0
922236,6,19,4,2149.0,1840,2251.0,1958,XE,2589,N13997,...,CLE,317,6.0,6.0,0,0.0,0.0,0.0,0.0,173.0

In [55]:
#Exercici 2: Resumeix estadísticament el dataset i les columnes d’interès. 
#Fes una anàlisi estadístic del que consideris rellevant.

archivo2 = aarchivo.drop(['Month', 'DayofMonth', 'DayOfWeek', 'FlightNum', 'TailNum' , 'Origin' , 'Dest' , 'Diverted'], axis='columns')
archivo2.describe()

,DepTime,CRSDepTime,ArrTime,CRSArrTime,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,200000.000000,200000.000000,199288.000000,200000.000000,199137.000000,199979.000000,199137.000000,199137.000000,200000.000000,200000.000000,199288.000000,199942.000000,128803.000000,128803.000000,128803.000000,128803.000000,128803.000000
mean,1518.997235,1468.291380,1610.352420,1635.839175,133.117944,134.119903,108.073939,42.295862,43.315655,764.315740,6.808408,18.246131,19.277307,3.629356,15.035527,0.099998,25.418686
std,450.153392,423.671447,548.236723,463.126733,71.760539,71.101514,68.394240,57.150915,53.828335,573.009134,5.236106,14.431018,44.192099,20.631518,34.018488,2.148459,42.330842
min,1.000000,0.000000,1.000000,1.000000,15.000000,-12.000000,0.000000,-68.000000,6.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1205.000000,1135.000000,1318.000000,1327.000000,80.000000,81.000000,58.000000,9.000000,12.000000,338.000000,4.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1545.000000,1510.000000,1715.000000,1707.000000,116.000000,116.000000,90.000000,24.000000,24.000000,606.000000,6.000000,14.000000,2.000000,0.000000,2.000000,0.000000,8.000000
75%,1900.000000,1815.000000,2030.000000,2014.000000,165.000000,165.000000,137.000000,56.000000,54.000000,997.000000,8.000000,21.000000,21.000000,0.000000,15.000000,0.000000,34.000000
max,2400.000000,2359.000000,2400.000000,2400.000000,675.000000,660.000000,654.000000,1370.000000,1521.000000,4962.000000,176.000000,364.000000,1286.000000,942.000000,1289.000000,357.000000,1184.000000

In [110]:
#Exercici 2: Troba quantes dades faltants hi ha per columna

aarchivo.isna().sum()

Month                    0
DayofMonth               0
DayOfWeek                0
DepTime                  0
CRSDepTime               0
ArrTime                712
CRSArrTime               0
UniqueCarrier            0
FlightNum                0
TailNum                  0
ActualElapsedTime      863
CRSElapsedTime          21
AirTime                863
ArrDelay               863
DepDelay                 0
Origin                   0
Dest                     0
Distance                 0
TaxiIn                 712
TaxiOut                 58
Diverted                 0
CarrierDelay         71197
WeatherDelay         71197
NASDelay             71197
SecurityDelay        71197
LateAircraftDelay    71197
dtype: int64

In [118]:
#Exercici 2: Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)

barchivo = aarchivo.assign(VelAir=np.nan, YesNoDelay='yes')
print (barchivo)

         Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
962501       6           8          7   1236.0        1205   1342.0
1041147      6           8          7    905.0         845   1130.0
281708       2          22          5   1446.0        1430   1711.0
559789       3          14          5   1237.0        1135   1410.0
1326529      8          22          5   1908.0        1842   2219.0
...        ...         ...        ...      ...         ...      ...
970573       6          12          4   2008.0        1809   2130.0
885759       6           5          4    652.0         625    906.0
1459066      9          10          3   1136.0        1020   1238.0
410944       3          31          1    929.0         920   1213.0
1332585      8          26          2   1705.0        1648   2024.0

         CRSArrTime UniqueCarrier  FlightNum TailNum  ...  TaxiIn  TaxiOut  \
962501         1309            UA        443  N331UA  ...     7.0     11.0
1041147        1110            AA        661  N253AA  ...    13.0     11.0
281708         1650            DL        150  N186DN  ...    18.0     40.0
559789         1307            CO        499  N75854  ...    10.0     17.0
1326529        2142            UA        302  N928UA  ...     4.0     30.0
...             ...           ...        ...     ...  ...     ...      ...
970573         1921            UA       1221  N332UA  ...    17.0     11.0
885759          900            WN       2896  N918WN  ...     5.0     10.0
1459066        1127            OO       5446  N292SW  ...     2.0     14.0
410944         1205            WN       2197  N419WN  ...     4.0      7.0
1332585        1955            UA        896  N329UA  ...     8.0     34.0

         Diverted  CarrierDelay  WeatherDelay NASDelay SecurityDelay  \
962501          0           8.0           0.0      2.0           0.0
1041147         0          20.0           0.0      0.0           0.0
281708          0           0.0          16.0      5.0           0.0
559789          0          62.0           0.0      1.0           0.0
1326529         0          11.0           0.0     11.0           0.0
...           ...           ...           ...      ...           ...
970573          0         119.0           0.0     10.0           0.0
885759          0           NaN           NaN      NaN           NaN
1459066         0          71.0           0.0      0.0           0.0
410944          0           NaN           NaN      NaN           NaN
1332585         0           0.0           0.0     29.0           0.0

         LateAircraftDelay  VelAir  YesNoDelay
962501                23.0     NaN         yes
1041147                0.0     NaN         yes
281708                 0.0     NaN         yes
559789                 0.0     NaN         yes
1326529               15.0     NaN         yes
...                    ...     ...         ...
970573                 0.0     NaN         yes
885759                 NaN     NaN         yes
1459066                0.0     NaN         yes
410944                 NaN     NaN         yes
1332585                0.0     NaN         yes

[200000 rows x 28 columns]

In [86]:
#Exercici 2: Fes una taula de les aerolínies amb més endarreriments acumulats:
# primer paso: filtro el archivo para tener solo los datos que me interesan 

completo = aarchivo[["UniqueCarrier","ArrDelay"]]
print(completo)

        UniqueCarrier  ArrDelay
962501             UA      33.0
1041147            AA      20.0
281708             DL      21.0
559789             CO      63.0
1326529            UA      37.0
...               ...       ...
970573             UA     129.0
885759             WN       6.0
1459066            OO      71.0
410944             WN       8.0
1332585            UA      29.0

[200000 rows x 2 columns]

In [87]:
#segundo paso: Filtro el archivo para tener solo las aerolineas con retrasos

soloretrasos = completo[completo['ArrDelay']>0]
print (soloretrasos)

        UniqueCarrier  ArrDelay
962501             UA      33.0
1041147            AA      20.0
281708             DL      21.0
559789             CO      63.0
1326529            UA      37.0
...               ...       ...
970573             UA     129.0
885759             WN       6.0
1459066            OO      71.0
410944             WN       8.0
1332585            UA      29.0

[177904 rows x 2 columns]

In [88]:
#Tercer paso: Agrupo por aerolineas los retrasos

Agruparetrasos = soloretrasos.groupby(['UniqueCarrier']).count()
print(Agruparetrasos)

               ArrDelay
UniqueCarrier
9E                 4713
AA                17769
AQ                   68
AS                 3640
B6                 4925
CO                 8569
DL                10452
EV                 7708
F9                 2705
FL                 6798
HA                  739
MQ                13564
NW                 7508
OH                 5175
OO                12631
UA                12678
US                 8605
WN                33398
XE                 9766
YV                 6493

In [90]:
#Cuarto paso: Pongo de mayor a menor las aerolineas con más retrasos acumulados

print(Agruparetrasos.sort_values(by=['ArrDelay'], ascending=False))

               ArrDelay
UniqueCarrier
WN                33398
AA                17769
MQ                13564
UA                12678
OO                12631
DL                10452
XE                 9766
US                 8605
CO                 8569
EV                 7708
NW                 7508
FL                 6798
YV                 6493
OH                 5175
B6                 4925
9E                 4713
AS                 3640
F9                 2705
HA                  739
AQ                   68

In [93]:
#Quins són els vols més llargs? 
#Primer paso: Extraigo las variables que me interesan

vueloslargos = aarchivo[["FlightNum","AirTime"]]
print(vueloslargos)

         FlightNum  AirTime
962501         443    108.0
1041147        661    121.0
281708         150     87.0
559789         499    126.0
1326529        302     97.0
...            ...      ...
970573        1221    174.0
885759        2896    119.0
1459066       5446     46.0
410944        2197    273.0
1332585        896     97.0

[200000 rows x 2 columns]

In [96]:
#Quins són els vols més llargs? 
#Segundo paso: como hay datos Nan, lo filtro para que sean solo los mayores a 0 
vueloslargos2 = vueloslargos[vueloslargos['AirTime']>0]
print (vueloslargos2)

         FlightNum  AirTime
962501         443    108.0
1041147        661    121.0
281708         150     87.0
559789         499    126.0
1326529        302     97.0
...            ...      ...
970573        1221    174.0
885759        2896    119.0
1459066       5446     46.0
410944        2197    273.0
1332585        896     97.0

[199136 rows x 2 columns]

In [97]:
#Quins són els vols més llargs? 
#Tercer paso: ordeno de mayor a menor y asi ya termino

ordervuelos = vueloslargos2.sort_values(by=['AirTime'], ascending=False)
print(ordervuelos)

        FlightNum  AirTime
556379         15    654.0
365249         15    637.0
556384         15    632.0
556364         15    631.0
179556         15    627.0
...           ...      ...
442113       2734      5.0
236330       5171      4.0
622668       6577      1.0
782709       5466      1.0
615069       5100      1.0

[199136 rows x 2 columns]

In [98]:
#Encuentra los vuelos más retrasados
#primer paso: extraigo las variables que me interesan 

vuelosmasretrasados = aarchivo[["FlightNum","ArrDelay"]]
print(vuelosmasretrasados)

         FlightNum  ArrDelay
962501         443      33.0
1041147        661      20.0
281708         150      21.0
559789         499      63.0
1326529        302      37.0
...            ...       ...
970573        1221     129.0
885759        2896       6.0
1459066       5446      71.0
410944        2197       8.0
1332585        896      29.0

[200000 rows x 2 columns]

In [99]:
#Encuentra los vuelos más retrasados
#segundo paso: como hay datos Nan, lo filtro para que sean solo los mayores a 0
vuelosmasretrasados2 = vuelosmasretrasados[vuelosmasretrasados['ArrDelay']>0]
print (vuelosmasretrasados2)

         FlightNum  ArrDelay
962501         443      33.0
1041147        661      20.0
281708         150      21.0
559789         499      63.0
1326529        302      37.0
...            ...       ...
970573        1221     129.0
885759        2896       6.0
1459066       5446      71.0
410944        2197       8.0
1332585        896      29.0

[177904 rows x 2 columns]

In [100]:
#Encuentra los vuelos más retrasados
#Tercer paso: ordeno de mayor a menor y asi ya termino sabiendo los vuelos más retrasados. 

vuelosmasretrasadosfinal = vuelosmasretrasados2.sort_values(by=['ArrDelay'], ascending=False)
print(vuelosmasretrasadosfinal)

         FlightNum  ArrDelay
545038        2093    1370.0
1716753       1790    1308.0
1025817        610    1289.0
1400101       1968    1286.0
1221849        123    1263.0
...            ...       ...
1754651         34       1.0
420451        2946       1.0
971143        1426       1.0
1278409         53       1.0
1535209       2169       1.0

[177904 rows x 2 columns]

In [107]:
#Busca les rutes més llargues 
#Paso 1: Elijo las variables que me interesan 
Rutaslargas = aarchivo[["Origin","Dest","Distance"]]
print(Rutaslargas)

#Paso 3: Agrupo por las variables. 
Rutaslargas2 = Rutaslargas.groupby(['Origin', 'Dest']).mean()
print(Rutaslargas2)

#Paso 3: Hago un orden primero por las mas largas, 
print(Rutaslargas2.sort_values(by=['Distance'], ascending=False))

        Origin Dest  Distance
962501     MSP  DEN       680
1041147    MSP  DFW       852
281708     ATL  JFK       760
559789     IAH  DEN       861
1326529    ORD  ALB       723
...        ...  ...       ...
970573     CMH  DEN      1155
885759     PDX  PHX      1009
1459066    SFO  SBP       191
410944     BWI  SLC      1864
1332585    ORD  ATL       606

[200000 rows x 3 columns]
             Distance
Origin Dest
ABE    ATL      692.0
       CLE      339.0
       CLT      481.0
       CVG      503.0
       DTW      424.0
...               ...
YUM    IPL       58.0
       LAS      238.0
       LAX      237.0
       PHX      160.0
       SLC      580.0

[4826 rows x 1 columns]
             Distance
Origin Dest
EWR    HNL     4962.0
HNL    EWR     4962.0
ATL    HNL     4502.0
HNL    ATL     4502.0
ORD    HNL     4243.0
...               ...
WRG    PSG       31.0
PSG    WRG       31.0
HPN    JFK       30.0
SJC    SFO       30.0
JFK    LGA       11.0

[4826 rows x 1 columns]

In [109]:
#Busca les rutes que acumulen más retrasos
#Paso 1: Elijo las variables que me interesan 
Rutasmasretrasos = aarchivo[["Origin","Dest","ArrDelay"]]
print(Rutasmasretrasos)


#Paso 2: Elimino los valores Nan al filtrar los datos. 
Rutasmasretrasos2 = Rutasmasretrasos[Rutasmasretrasos['ArrDelay']>0]
print(Rutasmasretrasos2)

#Paso 3: Agrupo por las variables. 
Rutasmasretrasos3 = Rutasmasretrasos2.groupby(['Origin', 'Dest']).count()
print(Rutaslargas3)


#Paso 3: Hago un orden primero por las mas largas, y luego por las más retrasadas. 
#Rutaslargas3 = Rutaslargas2.sort_values(by=['Distance'], ascending=False)
#print(Rutaslargas3)
print(Rutasmasretrasos3.sort_values(by=['ArrDelay'], ascending=False))

        Origin Dest  ArrDelay
962501     MSP  DEN      33.0
1041147    MSP  DFW      20.0
281708     ATL  JFK      21.0
559789     IAH  DEN      63.0
1326529    ORD  ALB      37.0
...        ...  ...       ...
970573     CMH  DEN     129.0
885759     PDX  PHX       6.0
1459066    SFO  SBP      71.0
410944     BWI  SLC       8.0
1332585    ORD  ATL      29.0

[200000 rows x 3 columns]
        Origin Dest  ArrDelay
962501     MSP  DEN      33.0
1041147    MSP  DFW      20.0
281708     ATL  JFK      21.0
559789     IAH  DEN      63.0
1326529    ORD  ALB      37.0
...        ...  ...       ...
970573     CMH  DEN     129.0
885759     PDX  PHX       6.0
1459066    SFO  SBP      71.0
410944     BWI  SLC       8.0
1332585    ORD  ATL      29.0

[177904 rows x 3 columns]
             Distance
Origin Dest
ABE    ATL          1
       CLE          1
       CLT          1
       CVG          1
       DTW          1
...               ...
YUM    IPL          1
       LAS          1
       LAX          1
       PHX          1
       SLC          1

[4826 rows x 1 columns]
             ArrDelay
Origin Dest
LAX    SFO        452
ORD    LGA        423
SFO    LAX        418
ATL    LGA        357
HOU    DAL        321
...               ...
DEN    PBI          1
MTJ    EWR          1
ATL    HDN          1
MTJ    ORD          1
GSP    MCO          1

[4781 rows x 1 columns]

In [ ]:
#Exporta el dataset net i amb les noves columnes a Excel.

barchivo.to_excel('datosavioneslimpios.xlsx')